"""initial database setup

Revision ID: 2bdcdb18add3
Revises: 
Create Date: 2024-10-24 16:00:10.433620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bdcdb18add3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_contact', sa.String(length=100), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('wholesaler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_daily', sa.Boolean(), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('report_time', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('front_register_amount', sa.Float(), nullable=False),
    sa.Column('back_register_amount', sa.Float(), nullable=False),
    sa.Column('credit_card_amount', sa.Float(), nullable=False),
    sa.Column('otc1_amount', sa.Float(), nullable=False),
    sa.Column('otc2_amount', sa.Float(), nullable=False),
    sa.Column('front_register_cash', sa.Float(), nullable=False),
    sa.Column('back_register_cash', sa.Float(), nullable=False),
    sa.Column('credit_card_total', sa.Float(), nullable=False),
    sa.Column('otc1_total', sa.Float(), nullable=False),
    sa.Column('otc2_total', sa.Float(), nullable=False),
    sa.Column('total_expected', sa.Float(), nullable=False),
    sa.Column('total_actual', sa.Float(), nullable=False),
    sa.Column('front_register_discrepancy', sa.Float(), nullable=False),
    sa.Column('back_register_discrepancy', sa.Float(), nullable=False),
    sa.Column('overall_discrepancy', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_sales_date'), ['date'], unique=False)

    op.create_table('order_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('wholesaler_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('finalized_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wholesaler_id'], ['wholesaler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('wholesaler_id', sa.Integer(), nullable=False),
    sa.Column('available_in_store', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['wholesaler_id'], ['wholesaler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('customer_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('custom_product_name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_order_id'], ['customer_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_list_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_list_id'], ['order_list.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('secure_url', sa.String(length=512), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sales_id'], ['daily_sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_documents')
    op.drop_table('order_list_item')
    op.drop_table('customer_order_item')
    op.drop_table('product')
    op.drop_table('order_list')
    with op.batch_alter_table('daily_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_sales_date'))

    op.drop_table('daily_sales')
    op.drop_table('wholesaler')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('customer_order')
    # ### end Alembic commands ###
