"""Add customer order models

Revision ID: 355f6f200fd7
Revises: d68e273abb8e
Create Date: 2024-10-18 00:34:58.991932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355f6f200fd7'
down_revision = 'd68e273abb8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_contact', sa.String(length=100), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_order_id'], ['customer_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_in_store', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('available_in_store')

    op.drop_table('customer_order_item')
    op.drop_table('customer_order')
    # ### end Alembic commands ###
