"""Add finalized_date to OrderList

Revision ID: d68e273abb8e
Revises: d928b5d616f2
Create Date: 2024-10-07 00:05:43.646280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68e273abb8e'
down_revision = 'd928b5d616f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalized_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_list', schema=None) as batch_op:
        batch_op.drop_column('finalized_date')

    # ### end Alembic commands ###
